version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: document_extractor_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: document_extractor
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_pass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    build: .
    container_name: document_extractor_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=document_extractor
      - DB_USER=api_user
      - DB_PASSWORD=api_pass123
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  mysql_data: